CREATE TABLE omrs_obs (
  obs_id INT not null,
  uuid CHAR(38) not null,
  patient_id INT not null,
  encounter_id INT,
  obs_date date,
  obs_time time,
  age_years_at_obs INT,
  age_months_at_obs INT,
  encounter_type VARCHAR(255),
  form VARCHAR(255),
  location VARCHAR(255),
  concept VARCHAR(255) not null,
  value_coded VARCHAR(255),
  value_date DATE DEFAULT NULL,
  value_numeric FLOAT DEFAULT NULL,
  value_text TEXT,
  comments VARCHAR(255),
  obs_group_id INT,
  date_created DATE
);
